In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_satisfaction = pd.read_csv("../data/지역별 의료서비스만족도(의원).csv", encoding='cp949')
df_satisfaction

     행정구역(시도)별(1)  특성별(1)  특성별(2) 2020  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
0    행정구역(시도)별(1)  특성별(1)  특성별(2)    계  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
1              전국      전체       계  100   17.1   40.7  35.6     6.3     0.3
2              전국   동·읍면부      동부  100     17   40.6  35.8     6.3     0.3
3              전국   동·읍면부     읍면부  100   17.6   41.5  34.3     6.5     0.2
4              전국      성별      남자  100   15.7   39.9  37.4     6.6     0.4
..            ...     ...     ...  ...    ...    ...   ...     ...     ...
106          경상남도      성별      남자  100   15.1   42.2  31.8    10.6     0.2
107          경상남도      성별      여자  100   16.4   42.8  33.6     6.7     0.5
108       제주특별자치도      전체       계  100   15.9   38.9  40.2     4.9     0.1
109       제주특별자치도      성별      남자  100   12.2   37.9  42.5     7.4       -
110       제주특별자치도      성별      여자  100     19   39.7  38.2     2.9     0.3

[111 rows x 9 columns]

In [3]:
result = df_satisfaction[df_satisfaction["행정구역(시도)별(1)"] != "전국"]
result

     행정구역(시도)별(1)  특성별(1)  특성별(2) 2020  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
0    행정구역(시도)별(1)  특성별(1)  특성별(2)    계  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
60          서울특별시      전체       계  100   19.8   38.5  36.7     4.7     0.3
61          서울특별시      성별      남자  100   19.4   37.9  38.1     4.5     0.2
62          서울특별시      성별      여자  100   20.2     39  35.6     4.8     0.4
63          부산광역시      전체       계  100   20.2     44  30.3     5.4     0.1
64          부산광역시      성별      남자  100     18   45.3  30.9     5.7     0.2
65          부산광역시      성별      여자  100   22.3   42.8  29.7     5.2       -
66          대구광역시      전체       계  100   14.6   42.5  36.6     6.3       -
67          대구광역시      성별      남자  100   11.6   43.4    36     9.1       -
68          대구광역시      성별      여자  100   17.2   41.8  37.2     3.8       -
69          인천광역시      전체       계  100   19.5   38.6  38.1     3.4     0.3
70          인천광역시      성별      남자  100     19   39.9  37.9     2.8     0.5
71          인천광역시      성별      여자  100     20   37.7  38.3     3.9     0.2
72          광주광역시      전체       계  100   15.4   44.5  33.7     6.5       -
73          광주광역시      성별      남자  100   13.2     45  32.3     9.5       -
74          광주광역시      성별      여자  100     17   44.2  34.7     4.1       -
75          대전광역시      전체       계  100   19.9   41.9  28.5     8.5     1.2
76          대전광역시      성별      남자  100   20.5   36.2  30.4      11     1.8
77          대전광역시      성별      여자  100   19.3   46.5  26.9     6.5     0.7
78          울산광역시      전체       계  100   16.4   44.4  35.3     3.3     0.7
79          울산광역시      성별      남자  100   13.8   40.4  42.4     2.8     0.6
80          울산광역시      성별      여자  100     19   48.5    28     3.9     0.7
81        세종특별자치시      전체       계  100   16.9   46.5  29.1     7.1     0.4
82        세종특별자치시      성별      남자  100     18   45.4  26.7     9.4     0.5
83        세종특별자치시      성별      여자  100     16   47.5    31     5.1     0.3
84            경기도      전체       계  100   14.7   39.2  37.8     8.1     0.3
85            경기도      성별      남자  100   13.7   37.8  40.4     7.8     0.3
86            경기도      성별      여자  100   15.5   40.4  35.6     8.4     0.2
87            강원도      전체       계  100   24.4   40.6  30.3     4.5     0.2
88            강원도      성별      남자  100   21.1   37.7  34.4     6.3     0.4
89            강원도      성별      여자  100   26.9   42.9  27.2     3.1       -
90           충청북도      전체       계  100   15.4   40.2  36.4     7.4     0.6
91           충청북도      성별      남자  100   13.6   39.9  38.3     7.4     0.8
92           충청북도      성별      여자  100   16.8   40.4  34.9     7.4     0.5
93           충청남도      전체       계  100     16   37.6  39.8     6.2     0.4
94           충청남도      성별      남자  100   13.6     34  45.5     6.6     0.3
95           충청남도      성별      여자  100   18.2     41  34.4     5.9     0.5
96           전라북도      전체       계  100     19   43.5  31.6     5.8     0.1
97           전라북도      성별      남자  100   16.4   43.2  34.7     5.7       -
98           전라북도      성별      여자  100     21   43.7  29.2     5.8     0.2
99           전라남도      전체       계  100     18   45.5  28.5     7.6     0.3
100          전라남도      성별      남자  100   15.8   46.5  32.4     5.4       -
101          전라남도      성별      여자  100   19.9   44.7  25.4     9.5     0.5
102          경상북도      전체       계  100   11.4   44.3  38.4     5.3     0.5
103          경상북도      성별      남자  100    8.8   43.4  40.8     5.8     1.2
104          경상북도      성별      여자  100   13.6   45.1  36.5     4.8       -
105          경상남도      전체       계  100   15.8   42.5  32.8     8.5     0.4
106          경상남도      성별      남자  100   15.1   42.2  31.8    10.6     0.2
107          경상남도      성별      여자  100   16.4   42.8  33.6     6.7     0.5
108       제주특별자치도      전체       계  100   15.9   38.9  40.2     4.9     0.1
109       제주특별자치도      성별      남자  100   12.2   37.9  42.5     7.4       -
110       제주특별자치도      성별      여자  100     19   39.7  38.2     2.9     0.3

In [4]:
result = result[result["특성별(1)"] == "전체"]
result

    행정구역(시도)별(1) 특성별(1) 특성별(2) 2020 매우 만족 약간 만족    보통 약간 불만족 매우 불만족
60         서울특별시     전체      계  100  19.8  38.5  36.7    4.7    0.3
63         부산광역시     전체      계  100  20.2    44  30.3    5.4    0.1
66         대구광역시     전체      계  100  14.6  42.5  36.6    6.3      -
69         인천광역시     전체      계  100  19.5  38.6  38.1    3.4    0.3
72         광주광역시     전체      계  100  15.4  44.5  33.7    6.5      -
75         대전광역시     전체      계  100  19.9  41.9  28.5    8.5    1.2
78         울산광역시     전체      계  100  16.4  44.4  35.3    3.3    0.7
81       세종특별자치시     전체      계  100  16.9  46.5  29.1    7.1    0.4
84           경기도     전체      계  100  14.7  39.2  37.8    8.1    0.3
87           강원도     전체      계  100  24.4  40.6  30.3    4.5    0.2
90          충청북도     전체      계  100  15.4  40.2  36.4    7.4    0.6
93          충청남도     전체      계  100    16  37.6  39.8    6.2    0.4
96          전라북도     전체      계  100    19  43.5  31.6    5.8    0.1
99          전라남도     전체      계  100    18  45.5  28.5    7.6    0.3
102         경상북도     전체      계  100  11.4  44.3  38.4    5.3    0.5
105         경상남도     전체      계  100  15.8  42.5  32.8    8.5    0.4
108      제주특별자치도     전체      계  100  15.9  38.9  40.2    4.9    0.1

In [5]:
result['만족 점수'] = (result['매우 만족'].astype(float)  * 0.01) + (result['약간 만족'].astype(float)  * 0.0075)+ (result['보통'].astype(float)  * 0.005) + (result['약간 불만족'].astype(float)  * 0.0025)

In [6]:
result

    행정구역(시도)별(1) 특성별(1) 특성별(2) 2020 매우 만족 약간 만족    보통 약간 불만족 매우 불만족    만족 점수
60         서울특별시     전체      계  100  19.8  38.5  36.7    4.7    0.3  0.68200
63         부산광역시     전체      계  100  20.2    44  30.3    5.4    0.1  0.69700
66         대구광역시     전체      계  100  14.6  42.5  36.6    6.3      -  0.66350
69         인천광역시     전체      계  100  19.5  38.6  38.1    3.4    0.3  0.68350
72         광주광역시     전체      계  100  15.4  44.5  33.7    6.5      -  0.67250
75         대전광역시     전체      계  100  19.9  41.9  28.5    8.5    1.2  0.67700
78         울산광역시     전체      계  100  16.4  44.4  35.3    3.3    0.7  0.68175
81       세종특별자치시     전체      계  100  16.9  46.5  29.1    7.1    0.4  0.68100
84           경기도     전체      계  100  14.7  39.2  37.8    8.1    0.3  0.65025
87           강원도     전체      계  100  24.4  40.6  30.3    4.5    0.2  0.71125
90          충청북도     전체      계  100  15.4  40.2  36.4    7.4    0.6  0.65600
93          충청남도     전체      계  100    16  37.6  39.8    6.2    0.4  0.65650
96          전라북도     전체      계  100    19  43.5  31.6    5.8    0.1  0.68875
99          전라남도     전체      계  100    18  45.5  28.5    7.6    0.3  0.68275
102         경상북도     전체      계  100  11.4  44.3  38.4    5.3    0.5  0.65150
105         경상남도     전체      계  100  15.8  42.5  32.8    8.5    0.4  0.66200
108      제주특별자치도     전체      계  100  15.9  38.9  40.2    4.9    0.1  0.66400

In [7]:
score_result = result[['행정구역(시도)별(1)', '만족 점수']]

In [8]:
score_result

    행정구역(시도)별(1)    만족 점수
60         서울특별시  0.68200
63         부산광역시  0.69700
66         대구광역시  0.66350
69         인천광역시  0.68350
72         광주광역시  0.67250
75         대전광역시  0.67700
78         울산광역시  0.68175
81       세종특별자치시  0.68100
84           경기도  0.65025
87           강원도  0.71125
90          충청북도  0.65600
93          충청남도  0.65650
96          전라북도  0.68875
99          전라남도  0.68275
102         경상북도  0.65150
105         경상남도  0.66200
108      제주특별자치도  0.66400

In [28]:
score_result.to_csv("./result/processed_지역별 의료서비스만족도(의원).csv", header=False, index=False, encoding='cp949')

In [10]:
df_satisfaction2 = pd.read_csv("../data/지역별 의료서비스만족도(병원).csv", encoding='cp949')
df_satisfaction2

     행정구역(시도)별(1)  특성별(1)  특성별(2) 2020  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
0    행정구역(시도)별(1)  특성별(1)  특성별(2)    계  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
1              전국      전체       계  100   24.1     39  28.2       8     0.7
2              전국   동·읍면부      동부  100   24.1   38.7  28.4     8.2     0.7
3              전국   동·읍면부     읍면부  100   24.1   40.6  27.1     7.4     0.8
4              전국      성별      남자  100   23.9   38.2  28.8     8.4     0.8
..            ...     ...     ...  ...    ...    ...   ...     ...     ...
106          경상남도      성별      남자  100     21   42.9  28.5     6.8     0.8
107          경상남도      성별      여자  100   25.8   39.3  27.3     7.3     0.4
108       제주특별자치도      전체       계  100     23   37.3  29.5     9.1     1.1
109       제주특별자치도      성별      남자  100   19.5   36.5  32.9     8.8     2.2
110       제주특별자치도      성별      여자  100   26.3     38  26.3     9.4       -

[111 rows x 9 columns]

In [11]:
result2 = df_satisfaction2[df_satisfaction2["행정구역(시도)별(1)"] != "전국"]
result2

     행정구역(시도)별(1)  특성별(1)  특성별(2) 2020  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
0    행정구역(시도)별(1)  특성별(1)  특성별(2)    계  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
60          서울특별시      전체       계  100   26.2     41  24.7     7.7     0.4
61          서울특별시      성별      남자  100   27.4   37.6  26.2     8.6     0.2
62          서울특별시      성별      여자  100   25.3   43.8  23.4       7     0.5
63          부산광역시      전체       계  100   27.4   38.7  23.1    10.6     0.2
64          부산광역시      성별      남자  100   27.8   38.2  23.2    10.8       -
65          부산광역시      성별      여자  100     27   39.1  23.1    10.5     0.4
66          대구광역시      전체       계  100   24.3   41.6    25     8.5     0.7
67          대구광역시      성별      남자  100   20.4   41.8  28.7       8     1.1
68          대구광역시      성별      여자  100   27.6   41.5  21.7     8.9     0.3
69          인천광역시      전체       계  100   23.4   33.6  33.1     8.8     1.1
70          인천광역시      성별      남자  100   21.9   36.4  29.6    10.9     1.2
71          인천광역시      성별      여자  100   24.7     31  36.4     6.8       1
72          광주광역시      전체       계  100   22.5     45  26.8     4.9     0.8
73          광주광역시      성별      남자  100   27.6   38.8  31.1     1.8     0.8
74          광주광역시      성별      여자  100     18   50.6    23     7.6     0.8
75          대전광역시      전체       계  100   27.6   35.5    28     6.5     2.5
76          대전광역시      성별      남자  100   28.3   38.5  25.3     4.8     3.1
77          대전광역시      성별      여자  100     27   32.6  30.5     8.1     1.9
78          울산광역시      전체       계  100   21.7   42.6  27.3     7.3     1.1
79          울산광역시      성별      남자  100   20.5   41.6  29.3     6.6       2
80          울산광역시      성별      여자  100   22.8   43.5  25.4       8     0.3
81        세종특별자치시      전체       계  100   23.4   41.4  26.1     9.2       -
82        세종특별자치시      성별      남자  100     24   44.4    23     8.6       -
83        세종특별자치시      성별      여자  100   22.8   38.8  28.8     9.6       -
84            경기도      전체       계  100   22.5   36.1  31.7     8.9     0.8
85            경기도      성별      남자  100   21.4   36.1  32.5     9.3     0.8
86            경기도      성별      여자  100   23.5   36.2    31     8.5     0.8
87            강원도      전체       계  100   28.1     42  25.4     4.4     0.2
88            강원도      성별      남자  100   26.7   41.6    27     4.4     0.3
89            강원도      성별      여자  100   29.4   42.3  23.9     4.3       -
90           충청북도      전체       계  100   24.6   39.8  24.7     9.1     1.8
91           충청북도      성별      남자  100   22.5   41.8  23.7    10.9     1.2
92           충청북도      성별      여자  100   26.9   37.7  25.8     7.3     2.4
93           충청남도      전체       계  100   24.5   38.8  30.4     5.9     0.4
94           충청남도      성별      남자  100   25.4   40.4  27.6     5.8     0.8
95           충청남도      성별      여자  100   23.7   37.4    33     5.9       -
96           전라북도      전체       계  100     25   39.1  28.1     7.2     0.6
97           전라북도      성별      남자  100   27.8   37.6  27.1     6.7     0.7
98           전라북도      성별      여자  100   22.3   40.6  28.9     7.6     0.5
99           전라남도      전체       계  100   23.5   40.5  27.3     8.1     0.7
100          전라남도      성별      남자  100   25.8   38.3  25.1    10.5     0.4
101          전라남도      성별      여자  100   21.3   42.6  29.4     5.7       1
102          경상북도      전체       계  100   18.3   41.6  31.4       8     0.9
103          경상북도      성별      남자  100   19.5   37.2    35     7.7     0.7
104          경상북도      성별      여자  100     17   46.4  27.4     8.2       1
105          경상남도      전체       계  100   23.5   41.1  27.9     7.1     0.6
106          경상남도      성별      남자  100     21   42.9  28.5     6.8     0.8
107          경상남도      성별      여자  100   25.8   39.3  27.3     7.3     0.4
108       제주특별자치도      전체       계  100     23   37.3  29.5     9.1     1.1
109       제주특별자치도      성별      남자  100   19.5   36.5  32.9     8.8     2.2
110       제주특별자치도      성별      여자  100   26.3     38  26.3     9.4       -

In [13]:
result2 = result2[result2["특성별(1)"] == "전체"]
result2

    행정구역(시도)별(1) 특성별(1) 특성별(2) 2020 매우 만족 약간 만족    보통 약간 불만족 매우 불만족
60         서울특별시     전체      계  100  26.2    41  24.7    7.7    0.4
63         부산광역시     전체      계  100  27.4  38.7  23.1   10.6    0.2
66         대구광역시     전체      계  100  24.3  41.6    25    8.5    0.7
69         인천광역시     전체      계  100  23.4  33.6  33.1    8.8    1.1
72         광주광역시     전체      계  100  22.5    45  26.8    4.9    0.8
75         대전광역시     전체      계  100  27.6  35.5    28    6.5    2.5
78         울산광역시     전체      계  100  21.7  42.6  27.3    7.3    1.1
81       세종특별자치시     전체      계  100  23.4  41.4  26.1    9.2      -
84           경기도     전체      계  100  22.5  36.1  31.7    8.9    0.8
87           강원도     전체      계  100  28.1    42  25.4    4.4    0.2
90          충청북도     전체      계  100  24.6  39.8  24.7    9.1    1.8
93          충청남도     전체      계  100  24.5  38.8  30.4    5.9    0.4
96          전라북도     전체      계  100    25  39.1  28.1    7.2    0.6
99          전라남도     전체      계  100  23.5  40.5  27.3    8.1    0.7
102         경상북도     전체      계  100  18.3  41.6  31.4      8    0.9
105         경상남도     전체      계  100  23.5  41.1  27.9    7.1    0.6
108      제주특별자치도     전체      계  100    23  37.3  29.5    9.1    1.1

In [15]:
result2['만족 점수'] = (result2['매우 만족'].astype(float)  * 0.01) + (result2['약간 만족'].astype(float)  * 0.0075)+ (result2['보통'].astype(float)  * 0.005) + (result2['약간 불만족'].astype(float)  * 0.0025)
result2

    행정구역(시도)별(1) 특성별(1) 특성별(2) 2020 매우 만족 약간 만족    보통 약간 불만족 매우 불만족    만족 점수
60         서울특별시     전체      계  100  26.2    41  24.7    7.7    0.4  0.71225
63         부산광역시     전체      계  100  27.4  38.7  23.1   10.6    0.2  0.70625
66         대구광역시     전체      계  100  24.3  41.6    25    8.5    0.7  0.70125
69         인천광역시     전체      계  100  23.4  33.6  33.1    8.8    1.1  0.67350
72         광주광역시     전체      계  100  22.5    45  26.8    4.9    0.8  0.70875
75         대전광역시     전체      계  100  27.6  35.5    28    6.5    2.5  0.69850
78         울산광역시     전체      계  100  21.7  42.6  27.3    7.3    1.1  0.69125
81       세종특별자치시     전체      계  100  23.4  41.4  26.1    9.2      -  0.69800
84           경기도     전체      계  100  22.5  36.1  31.7    8.9    0.8  0.67650
87           강원도     전체      계  100  28.1    42  25.4    4.4    0.2  0.73400
90          충청북도     전체      계  100  24.6  39.8  24.7    9.1    1.8  0.69075
93          충청남도     전체      계  100  24.5  38.8  30.4    5.9    0.4  0.70275
96          전라북도     전체      계  100    25  39.1  28.1    7.2    0.6  0.70175
99          전라남도     전체      계  100  23.5  40.5  27.3    8.1    0.7  0.69550
102         경상북도     전체      계  100  18.3  41.6  31.4      8    0.9  0.67200
105         경상남도     전체      계  100  23.5  41.1  27.9    7.1    0.6  0.70050
108      제주특별자치도     전체      계  100    23  37.3  29.5    9.1    1.1  0.68000

In [33]:
score_result2 = result2[['행정구역(시도)별(1)', '만족 점수']]
score_result2

    행정구역(시도)별(1)    만족 점수
60         서울특별시  0.71225
63         부산광역시  0.70625
66         대구광역시  0.70125
69         인천광역시  0.67350
72         광주광역시  0.70875
75         대전광역시  0.69850
78         울산광역시  0.69125
81       세종특별자치시  0.69800
84           경기도  0.67650
87           강원도  0.73400
90          충청북도  0.69075
93          충청남도  0.70275
96          전라북도  0.70175
99          전라남도  0.69550
102         경상북도  0.67200
105         경상남도  0.70050
108      제주특별자치도  0.68000

In [27]:
score_result2.to_csv("./result/processed_지역별 의료서비스만족도(병원).csv", header=False, index=False, encoding='cp949')

In [34]:
score_result

    행정구역(시도)별(1)    만족 점수
60         서울특별시  0.68200
63         부산광역시  0.69700
66         대구광역시  0.66350
69         인천광역시  0.68350
72         광주광역시  0.67250
75         대전광역시  0.67700
78         울산광역시  0.68175
81       세종특별자치시  0.68100
84           경기도  0.65025
87           강원도  0.71125
90          충청북도  0.65600
93          충청남도  0.65650
96          전라북도  0.68875
99          전라남도  0.68275
102         경상북도  0.65150
105         경상남도  0.66200
108      제주특별자치도  0.66400

In [36]:
score_result2
df_result = score_result

In [37]:
df_result["만족 점수2"] = score_result2['만족 점수']

In [38]:
df_result

    행정구역(시도)별(1)    만족 점수   만족 점수2
60         서울특별시  0.68200  0.71225
63         부산광역시  0.69700  0.70625
66         대구광역시  0.66350  0.70125
69         인천광역시  0.68350  0.67350
72         광주광역시  0.67250  0.70875
75         대전광역시  0.67700  0.69850
78         울산광역시  0.68175  0.69125
81       세종특별자치시  0.68100  0.69800
84           경기도  0.65025  0.67650
87           강원도  0.71125  0.73400
90          충청북도  0.65600  0.69075
93          충청남도  0.65650  0.70275
96          전라북도  0.68875  0.70175
99          전라남도  0.68275  0.69550
102         경상북도  0.65150  0.67200
105         경상남도  0.66200  0.70050
108      제주특별자치도  0.66400  0.68000

In [39]:
df_result['종합 만족 점수'] = (df_result['만족 점수'].astype(float) + df_result['만족 점수2'].astype(float)) / 2

In [41]:
df_result = df_result[['행정구역(시도)별(1)', '종합 만족 점수']]

In [42]:
df_result

    행정구역(시도)별(1)  종합 만족 점수
60         서울특별시  0.697125
63         부산광역시  0.701625
66         대구광역시  0.682375
69         인천광역시  0.678500
72         광주광역시  0.690625
75         대전광역시  0.687750
78         울산광역시  0.686500
81       세종특별자치시  0.689500
84           경기도  0.663375
87           강원도  0.722625
90          충청북도  0.673375
93          충청남도  0.679625
96          전라북도  0.695250
99          전라남도  0.689125
102         경상북도  0.661750
105         경상남도  0.681250
108      제주특별자치도  0.672000

In [43]:
df_result.to_csv("./result/processed_지역별 의료서비스만족도(종합).csv", header=False, index=False, encoding='cp949')